{{ if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-arangodb-crd.name" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.webhook.annotations }}
annotations:
{{ toYaml .Values.webhook.annotations | indent 8 }}
{{- end }}
labels:
  app.kubernetes.io/name: {{ template "kube-arangodb-crd.name" . }}
  helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  strategy:
{{ toYaml .Values.webhook.updateStrategy | indent 8 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kube-arangodb-crd.name" . }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "kube-arangodb-crd.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
{{- if .Values.webhook.annotations }}
      annotations:
{{ toYaml .Values.webhook.annotations | indent 16 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "kube-arangodb-crd.name" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ template "kube-arangodb-crd.name" . }}
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: operator
          imagePullPolicy: {{ .Values.webhook.imagePullPolicy }}
          image: {{ .Values.webhook.image }}
          args:
            - "webhook"
            - "--host=0.0.0.0"
            - "--port=8443"
            - "--cert=/etc/webhook/tls/tls.crt"
            - "--key=/etc/webhook/tls/tls.key"
          ports:
            - name: webhook
              containerPort: 443
          volumeMounts:
            - name: tls
              mountPath: "/etc/webhook/tls"
              readOnly: true
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - 'ALL'
{{- if .Values.webhook.resources }}
          resources:
{{ toYaml .Values.webhook.resources | indent 22 }}
{{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ template "kube-arangodb-crd.name" . }}
{{ end }}