{{ if .Values.webhook.enabled }}
{{- $altNames := list ( printf "%s.%s" (include "kube-arangodb-crd.name" .) .Release.Namespace ) ( printf "%s.%s.svc" (include "kube-arangodb-crd.name" .) .Release.Namespace ) -}}
{{- $ca := genCA "kube-arangodb-ca" 3650 -}}
{{- $cert := genSignedCert ( include "kube-arangodb-crd.name" . ) nil $altNames 3650 $ca -}}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "kube-arangodb-crd.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "kube-arangodb-crd.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}

{{ if .Values.webhook.validation }}

---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: "webhook.arangodb.com"
webhooks:
  - name: "deployment.webhook.arangodb.com"
    rules:
      - apiGroups:
          - "database.arangodb.com"
        apiVersions:
          - "v1"
          - "v1alpha"
        operations:
          - "CREATE"
        resources:
          - "arangodeployments"
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "kube-arangodb-crd.name" . }}
        path: "/validate"
      caBundle: {{ b64enc $ca.Cert }}
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5

{{ end }}
{{ end }}